version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_DB: "disk-store-db"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "1234"
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: